from utils import *
profile = Profile()                                                                                                                                   
profile.points.append({"lat" : 45.1667, "lng" : 5.7, "alt" : 0, "distance" : 0})                                                                      
profile.points.append({"lat" : 45.2667, "lng" : 5.7, "alt" : 0, "distance" : 5000})                                                                   
profile.points.append({"lat" : 45.1667, "lng" : 5.7, "alt" : 0, "distance" : 10000})                                                                  
profile.intervals.append({"length" : 5000, "elevation" : 0, "grade" : 0.0, "distance" : 5000, "cum_elevation" : 0})                                   
profile.intervals.append({"length" : 5000, "elevation" : 0, "grade" : 0.0, "distance" : 10000, "cum_elevation" : 0})
profile.add_wind(20.0/3.6, 0.0)
params =  (75, 1.0, 0.18, 0.0)
x0 = profile.optimal_power(params, 300, constant_velocity=True)
x1 = profile.optimal_power(params, 300, constant_velocity=True, use_nominal=False)
x2 = profile.optimal_power(params, 300, constant_power=True)
x3 = profile.optimal_power(params, 300)
